version: "3"

services:
  # Redis cache
  redis:
    image: redis:4.0.9-alpine
    restart: always
  
  # Configure correctly the redis cache to enable notifications
  redis-configure:
    image: redis:4.0.9-alpine
    entrypoint: sh
    command: -c "redis-cli -h redis config set notify-keyspace-events K$$"
    depends_on:
    - redis
    links:
    - redis

  # Start the listener
  listener:
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: run start-listener
    environment:
      - REDIS_HOST=redis
    ports:
    - 3004:3004
    restart: always
    depends_on:
    - redis
    links:
    - redis
  
  # Start the emitter
  emitter:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: run start-emitter
    environment:
      - REDIS_HOST=redis
    ports:
    - 3003:3003
    restart: always
    depends_on:
    - redis
    links:
    - redis